from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import pandas as pd
import numpy as np
import os

app = Flask(__name__)
CORS(app)   # allow cross-origin requests from Express backend

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# =============================================================================
# LOAD ML ARTIFACTS
# =============================================================================
# Generated by running train_model.py once.
# Must be in the same folder as this file.
# =============================================================================

try:
    model           = joblib.load(os.path.join(BASE_DIR, 'model.pkl'))
    scaler          = joblib.load(os.path.join(BASE_DIR, 'scaler.pkl'))
    feature_columns = joblib.load(os.path.join(BASE_DIR, 'feature_columns.pkl'))
    print("=" * 55)
    print("   model.pkl           loaded successfully")
    print("   scaler.pkl          loaded successfully")
    print("   feature_columns.pkl loaded successfully")
    print(f"  Features: {feature_columns}")
    print("=" * 55)
except FileNotFoundError as e:
    print(f"\n  ERROR: {e}")
    print("  Run train_model.py first to generate model artifacts.")
    exit(1)


# =============================================================================
# LOAD CSV — Build email → donation history lookup table
# =============================================================================
# MongoDB donors only have profile info (name, blood group, phone, etc.)
# The CSV is the source of truth for donation history.
# We match donors by email to get their history for ML scoring.
# =============================================================================

CSV_FILENAME = 'blood donor list final wala.csv'
csv_path     = os.path.join(BASE_DIR, CSV_FILENAME)

DONOR_HISTORY = {}   # { "email@example.com": { months_since_first_donation, ... } }

try:
    df_csv = pd.read_csv(csv_path)

    for _, row in df_csv.iterrows():
        email = str(row.get('email', '')).strip().lower()
        if email:
            DONOR_HISTORY[email] = {
                'months_since_first_donation': int(row.get('months_since_first_donation', 0)),
                'number_of_donation':          int(row.get('number_of_donation', 0)),
                'pints_donated':               int(row.get('pints_donated', 0)),
                'blood_group':                 str(row.get('blood_group', 'O+')).strip(),
            }

    print("=" * 55)
    print(f"  CSV loaded : {len(DONOR_HISTORY)} donor records indexed by email")
    print(f"  CSV file   : {CSV_FILENAME}")
    print("=" * 55)

except FileNotFoundError:
    print(f"\n  WARNING: '{CSV_FILENAME}' not found in {BASE_DIR}")
    print("  /donor-history will return null for all emails.")
    print("  Place the CSV in the same folder as app.py.\n")


# =============================================================================
# HELPERS
# =============================================================================

def build_features(donor):
    """
    Takes a donor dict (with history fields already attached from CSV lookup)
    and engineers the 4 numeric + blood_group features the trained model expects.

    Required fields:
        months_since_first_donation : int
        number_of_donation          : int
        pints_donated               : int
        blood_group                 : str  e.g. 'A+', 'O-', 'AB+'

    Optional (identity only, not used in prediction):
        email    : str
        username : str
    """
    n = int(donor.get('number_of_donation', 0))
    m = int(donor.get('months_since_first_donation', 0))
    p = int(donor.get('pints_donated', 0))

    # Derived features — same logic as train_model.py
    avg_gap            = round(m / n, 4) if n > 0 else 0
    donation_frequency = round(n / m, 4) if m > 0 else 0
    avg_pints          = round(p / n, 4) if n > 0 else 0

    row = {
        'months_since_first_donation': m,
        'avg_gap':                     avg_gap,
        'donation_frequency':          donation_frequency,
        'avg_pints_per_donation':      avg_pints,
        'blood_group':                 donor.get('blood_group', 'O+')
    }

    df = pd.DataFrame([row])

    # One-hot encode blood_group to match training format
    df = pd.get_dummies(df, columns=['blood_group'])

    # Add any missing blood group columns with 0
    # (e.g. if this donor is A+, all other blood group dummies = 0)
    for col in feature_columns:
        if col not in df.columns:
            df[col] = 0

    # Enforce exact column order from training
    df = df[feature_columns]
    return df


def get_priority(probability):
    """Convert ML probability (0.0–1.0) to human-readable priority label."""
    if probability >= 0.75:
        return 'HIGH'
    elif probability >= 0.45:
        return 'MEDIUM'
    else:
        return 'LOW'


def score_donor(donor):
    """
    Score a single donor dict through the ML pipeline.
    The donor dict must already contain history fields
    (fetched from CSV via /donor-history or provided directly).

    Returns a result dict with probability, priority, and identity fields.
    """
    features_df = build_features(donor)
    scaled      = scaler.transform(features_df)
    prediction  = int(model.predict(scaled)[0])
    probability = round(float(model.predict_proba(scaled)[0][1]), 4)

    return {
        'email':             donor.get('email', ''),
        'username':          donor.get('username') or donor.get('name', ''),
        'blood_group':       donor.get('blood_group', ''),
        'probability':       probability,
        'is_frequent_donor': prediction,
        'label':             'Frequent Donor' if prediction == 1 else 'Infrequent Donor',
        'priority':          get_priority(probability),
        'found_in_csv':      donor.get('found_in_csv', False),
    }


# =============================================================================
# ROUTE 1 — Health Check
# GET /health
# =============================================================================
# Express calls this on startup to confirm the ML server is alive.
#
# Response:
# {
#     "status":     "running",
#     "message":    "Daan ML Server is active",
#     "csv_donors": 9931,
#     "model":      "Logistic Regression — Frequent Donor Predictor"
# }
# =============================================================================

@app.route('/health', methods=['GET'])
def health():
    return jsonify({
        'status':     'running',
        'message':    'Daan ML Server is active',
        'model':      'Logistic Regression — Frequent Donor Predictor',
        'csv_donors': len(DONOR_HISTORY),
        'note':       'Donors matched to CSV by email for donation history',
    }), 200


# =============================================================================
# ROUTE 2 — Donor History Lookup
# POST /donor-history
# =============================================================================
# Express sends a list of donor emails.
# Flask looks each one up in the CSV and returns their donation history.
# Donors not found in the CSV get null — Express treats them as new donors
# and sends 0s for all history fields to the ML model.
#
# Request body:
# {
#     "emails": ["ram@gmail.com", "sita@yahoo.com", ...]
# }
#
# Response:
# {
#     "ram@gmail.com":  {
#         "months_since_first_donation": 65,
#         "number_of_donation": 31,
#         "pints_donated": 62,
#         "blood_group": "A+"
#     },
#     "sita@yahoo.com": null    ← not found in CSV (new donor)
# }
# =============================================================================

@app.route('/donor-history', methods=['POST'])
def donor_history():
    try:
        body = request.get_json()
        if not body:
            return jsonify({'error': 'Request body is empty'}), 400

        emails = body.get('emails', [])
        if not isinstance(emails, list):
            return jsonify({'error': 'emails must be an array of strings'}), 400

        result    = {}
        found     = 0
        not_found = 0

        for email in emails:
            key     = str(email).strip().lower()
            history = DONOR_HISTORY.get(key, None)
            result[email] = history   # None if not found in CSV
            if history:
                found += 1
            else:
                not_found += 1

        print(f"\n  /donor-history  — {len(emails)} emails queried")
        print(f"   Found     : {found}")
        print(f"   Not found : {not_found} (will score as new donors with 0 history)")

        return jsonify(result), 200

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# =============================================================================
# ROUTE 3 — Predict Single Donor
# POST /predict
# =============================================================================
# Score one specific donor.
# The donor object must already have history fields attached
# (either fetched from CSV via /donor-history first, or manually provided).
#
# Request body:
# {
#     "email":                        "ram@gmail.com",
#     "username":                     "Ram Pandey",
#     "blood_group":                  "O+",
#     "months_since_first_donation":  55,
#     "number_of_donation":           20,
#     "pints_donated":                20,
#     "found_in_csv":                 true
# }
#
# Response:
# {
#     "email":             "ram@gmail.com",
#     "username":          "Ram Pandey",
#     "blood_group":       "O+",
#     "probability":       0.7821,
#     "is_frequent_donor": 1,
#     "label":             "Frequent Donor",
#     "priority":          "HIGH",
#     "found_in_csv":      true
# }
# =============================================================================

@app.route('/predict', methods=['POST'])
def predict_single():
    try:
        donor = request.get_json()

        if not donor:
            return jsonify({'error': 'Request body is empty'}), 400

        required = [
            'months_since_first_donation',
            'number_of_donation',
            'pints_donated',
            'blood_group'
        ]
        missing = [f for f in required if f not in donor]
        if missing:
            return jsonify({
                'error':   'Missing required fields',
                'missing': missing,
                'hint':    'Fetch history from /donor-history first, then call /predict'
            }), 400

        result = score_donor(donor)
        return jsonify(result), 200

    except Exception as e:
        return jsonify({'error': str(e)}), 500


# =============================================================================
# ROUTE 4 — Predict + Rank Batch  (PRIMARY EMERGENCY ROUTE)
# POST /predict-batch
# =============================================================================
# Scores and ranks a list of donors by ML probability.
# Each donor object must already have history fields attached.
# The Express /score-emergency-donors route handles enrichment
# by calling /donor-history first, then calling this route.
#
# Request body:
# {
#     "hospital_city":      "Kathmandu",
#     "blood_group_needed": "O+",
#     "donors": [
#         {
#             "email":                       "ram@gmail.com",
#             "username":                    "Ram Pandey",
#             "blood_group":                 "O+",
#             "months_since_first_donation": 55,
#             "number_of_donation":          20,
#             "pints_donated":               20,
#             "found_in_csv":                true
#         },
#         ...
#     ]
# }
#
# Response:
# {
#     "hospital_city":      "Kathmandu",
#     "blood_group_needed": "O+",
#     "total_donors":       5,
#     "high_priority":      2,
#     "medium_priority":    2,
#     "low_priority":       1,
#     "skipped":            0,
#     "csv_matched":        4,
#     "ranked_donors": [
#         {
#             "rank":              1,
#             "email":             "ram@gmail.com",
#             "username":          "Ram Pandey",
#             "blood_group":       "O+",
#             "probability":       0.8731,
#             "is_frequent_donor": 1,
#             "label":             "Frequent Donor",
#             "priority":          "HIGH",
#             "found_in_csv":      true
#         },
#         ...
#     ]
# }
# =============================================================================

@app.route('/predict-batch', methods=['POST'])
def predict_batch():
    try:
        body = request.get_json()

        if not body:
            return jsonify({'error': 'Request body is empty'}), 400

        if 'donors' not in body:
            return jsonify({
                'error': 'donors array is required',
                'hint':  'Send { hospital_city, blood_group_needed, donors: [...] }'
            }), 400

        donors             = body.get('donors', [])
        hospital_city      = body.get('hospital_city', '')
        blood_group_needed = body.get('blood_group_needed', '')

        print(f"\n  Emergency batch request")
        print(f"   City         : {hospital_city}")
        print(f"   Blood needed : {blood_group_needed}")
        print(f"   Donors sent  : {len(donors)}")

        # Handle empty donor list
        if len(donors) == 0:
            return jsonify({
                'hospital_city':      hospital_city,
                'blood_group_needed': blood_group_needed,
                'total_donors':       0,
                'high_priority':      0,
                'medium_priority':    0,
                'low_priority':       0,
                'skipped':            0,
                'csv_matched':        0,
                'ranked_donors':      [],
                'message':            f'No donors found for {blood_group_needed} in {hospital_city}'
            }), 200

        # Score every donor
        # If one donor has bad/missing data, skip without crashing the whole batch
        results = []
        skipped = 0

        for donor in donors:
            try:
                result = score_donor(donor)
                results.append(result)
            except Exception as donor_error:
                skipped += 1
                print(f"   Skipped {donor.get('email', 'unknown')}: {donor_error}")
                results.append({
                    'email':             donor.get('email', ''),
                    'username':          donor.get('username') or donor.get('name', ''),
                    'blood_group':       donor.get('blood_group', ''),
                    'probability':       0.0,
                    'is_frequent_donor': 0,
                    'label':             'Infrequent Donor',
                    'priority':          'LOW',
                    'found_in_csv':      donor.get('found_in_csv', False),
                    'error':             str(donor_error)
                })

        # Sort by probability — highest first
        results.sort(key=lambda x: x['probability'], reverse=True)

        # Add rank numbers after sorting
        for i, r in enumerate(results):
            r['rank'] = i + 1

        # Count priority tiers
        high_count   = sum(1 for r in results if r['priority'] == 'HIGH')
        medium_count = sum(1 for r in results if r['priority'] == 'MEDIUM')
        low_count    = sum(1 for r in results if r['priority'] == 'LOW')
        csv_matched  = sum(1 for r in results if r.get('found_in_csv'))

        print(f"   Scored      : {len(results)} donors")
        print(f"   CSV matched : {csv_matched} (used real history)")
        print(f"   New donors  : {len(results) - csv_matched} (scored with 0 history)")
        print(f"   HIGH        : {high_count}")
        print(f"   MEDIUM      : {medium_count}")
        print(f"   LOW         : {low_count}")
        if skipped > 0:
            print(f"   Skipped     : {skipped} (bad/missing data)")

        return jsonify({
            'hospital_city':      hospital_city,
            'blood_group_needed': blood_group_needed,
            'total_donors':       len(results),
            'high_priority':      high_count,
            'medium_priority':    medium_count,
            'low_priority':       low_count,
            'skipped':            skipped,
            'csv_matched':        csv_matched,
            'ranked_donors':      results
        }), 200

    except Exception as e:
        print(f"   Server error: {e}")
        return jsonify({'error': str(e)}), 500


# =============================================================================
# RUN SERVER
# =============================================================================

if __name__ == '__main__':
    print("\n" + "=" * 55)
    print("   Daan ML Server — Blood Donor Predictor")
    print("=" * 55)
    print("  URL    : http://localhost:5001")
    print("  Routes :")
    print("    GET  /health          → health check + CSV status")
    print("    POST /donor-history   → lookup CSV history by email list")
    print("    POST /predict         → score single donor")
    print("    POST /predict-batch   → score + rank donor batch (MAIN)")
    print("=" * 55 + "\n")
    app.run(host='0.0.0.0', port=5001, debug=True)